catch(int e){
        cout<<"exception no:"<<e<<endl;
    }

    catch(string e)
    {
        cout<<"exception handled::"<<e<<endl;
    }